const CREATE_POST = 'CREATE_POST';
const UPDATE_POST = 'UPDATE_POST';
const DELETE_POST = 'DELETE_POST';
const LIKE_POST = 'LIKE_POST';
const FETCH_ALL = 'FETCH_ALL';
export {CREATE_POST, LIKE_POST, DELETE_POST, UPDATE_POST, FETCH_ALL};